name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - master
      - feature/actions

permissions:
  contents: read
  packages: write  # Необходимо для публикации в GHCR

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование кода
      - name: Checkout code
        uses: actions/checkout@v3

      # Шаг 2: Установка JDK 11
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      # Шаг 3: Сборка приложения Maven
      - name: Build with Maven
        run: mvn clean package

      # Шаг 4: Установка переменной REPO_NAME в нижнем регистре
      - name: Set Docker repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Шаг 5: Проверка значения REPO_NAME (опционально)
      - name: Print REPO_NAME
        run: echo "REPO_NAME is $REPO_NAME"

      # Шаг 6: Логин в GHCR
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Шаг 7: Сборка Docker-образа
      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner | toLower }}/finance-planner:${{ github.run_number }} .

      # Шаг 8: Публикация Docker-образа в GHCR
      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ github.repository_owner | toLower }}/finance-planner:${{ github.run_number }}

  deploy:
    needs: build_and_publish
    runs-on: ubuntu-latest

    steps:
      # Шаг 9: Установка переменной REPO_NAME в нижнем регистре
      - name: Set Docker repository name
        run: echo "REPO_NAME=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      # Шаг 10: Деплой на сервер через SSH
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 82.146.40.100
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo ${{ secrets.GHCR_PAT }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/$REPO_NAME/finance-planner:${{ github.run_number }}
            if [ "$(docker ps -q -f name=finance-planner)" ]; then
            docker stop finance-planner
            docker rm finance-planner
            fi